//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 05:14:24 PM CEST 
//


package orgExampleFahrradverleih;

import java.math.BigInteger;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
//import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ausleih_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ausleih_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rueckgabeort" type="{http://www.example.org/FahrradVerleih}koord_type"/>
 *         &lt;element name="mietBeginn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mietEnde" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ausleih_type", propOrder = {
    "rueckgabeort",
    "mietBeginn",
    "mietEnde"
})
public class AusleihType {

    @XmlElement(required = true)
    protected String rueckgabeort;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected String mietBeginn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected String mietEnde;
   

    
    public AusleihType() {
    	
	}
    
    
    /********* EIGENER TEIL **********/
    public AusleihType(String rueckgabeOrt, String mietBeginn, String mietEnde ) {
    	setRueckgabeort(rueckgabeOrt);
    	setMietBeginn(mietBeginn);
    	setMietEnde(mietEnde);
    }
    
    
    
    /*public AusleihType(String rueckgabeOrt2, String mietBeginn2,
			String mietEnde2) throws DatatypeConfigurationException {
    	setRueckgabeort(rueckgabeOrt2);
    	XMLGregorianCalendar date2 = buildXmlCalender(mietBeginn2);
    	
    	setMietBeginn(date2);
    	setMietEnde(buildXmlCalender(mietEnde2));
    	
	}


	private XMLGregorianCalendar buildXmlCalender(String mietBeginn2)
			throws DatatypeConfigurationException {
		GregorianCalendar c = new GregorianCalendar();
    	c.setTime(new Date(mietBeginn2));
    	
    	XMLGregorianCalendar date2 = DatatypeFactory.newInstance().newXMLGregorianCalendar(c);
		return date2;
	}*/


	/**
     * Gets the value of the rueckgabeort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRueckgabeort() {
        return rueckgabeort;
    }

    /**
     * Sets the value of the rueckgabeort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRueckgabeort(String value) {
        this.rueckgabeort = value;
    }

   

    /**
     * Gets the value of the mietBeginn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMietBeginn() {
        return mietBeginn;
    }

    /**
     * Sets the value of the mietBeginn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMietBeginn(String value) {
        this.mietBeginn = value;
    }

    /**
     * Gets the value of the mietEnde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMietEnde() {
        return mietEnde;
    }

    /**
     * Sets the value of the mietEnde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMietEnde(String value) {
        this.mietEnde = value;
    }

}
