//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 05:14:24 PM CEST 
//


package orgExampleFahrradverleih;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="users" type="{http://www.example.org/FahrradVerleih}users_type"/>
 *         &lt;element name="fahrraeder" type="{http://www.example.org/FahrradVerleih}fahrraeder_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "users",
    "fahrraeder"
})
@XmlRootElement(name = "collection")
public class Collection {

    @XmlElement(required = true)
    protected UsersType users;
    @XmlElement(required = true)
    protected FahrraederType fahrraeder;

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link UsersType }
     *     
     */
    public UsersType getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersType }
     *     
     */
    public void setUsers(UsersType value) {
        this.users = value;
    }

    /**
     * Gets the value of the fahrraeder property.
     * 
     * @return
     *     possible object is
     *     {@link FahrraederType }
     *     
     */
    public FahrraederType getFahrraeder() {
        return fahrraeder;
    }

    /**
     * Sets the value of the fahrraeder property.
     * 
     * @param value
     *     allowed object is
     *     {@link FahrraederType }
     *     
     */
    public void setFahrraeder(FahrraederType value) {
        this.fahrraeder = value;
    }

}
