//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 05:14:24 PM CEST 
//


package orgExampleFahrradverleih;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import orgExampleFahrradverleih.AusleihType;
import orgExampleFahrradverleih.ModelType;
import orgExampleFahrradverleih.VergebenAnType;



/**
 * <p>Java class for fahrrad_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fahrrad_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bild" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="standort" type="{http://www.example.org/FahrradVerleih}koord_type"/>
 *         &lt;element name="hersteller" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rahmenNr" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="model" type="{http://www.example.org/FahrradVerleih}model_type"/>
 *         &lt;element name="vergebenAn" type="{http://www.example.org/FahrradVerleih}vergebenAn_type"/>
 *         &lt;element name="ausleih" type="{http://www.example.org/FahrradVerleih}ausleih_type"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="BesitzerID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="preis" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fahrrad_type", propOrder = {
    "bild",
    "standort",
    "hersteller",
    "rahmenNr",
    "model",
    "vergebenAn",
    "ausleih"
})
public class FahrradType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String bild;
    @XmlElement(required = true)
    protected String standort;
    @XmlElement(required = true)
    protected String hersteller;
    @XmlElement(required = true)
    protected BigInteger rahmenNr;
    @XmlElement(required = true)
    protected ModelType model;
    @XmlElement(required = true)
    protected VergebenAnType vergebenAn;
    @XmlElement(required = true)
    protected AusleihType ausleih;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "BesitzerID", required = true)
    protected BigInteger besitzerID;
    @XmlAttribute(name = "preis")
    protected Float preis;

    
 public FahrradType() {
    	
   	}


    /********* EIGENER TEIL **********/
    public FahrradType(Integer id, Integer besitzer, ModelType model, String hersteller, Integer rahmenNr, String bild, String standort, float preis, Integer vergebenAn) {
    	this(id, besitzer, model, hersteller, rahmenNr, bild,standort,preis);
    	setVergebenAn(new VergebenAnType(vergebenAn));
    }
    

    
    
    /********* EIGENER TEIL **********/
    public FahrradType(Integer id, Integer besitzer, ModelType model, String hersteller, Integer rahmenNr, String bild, String standort, float preis ) {
    	
    	setId(id);
    	setBesitzerID(besitzer);
    	setModel(model);
    	setHersteller(hersteller);
    	setRahmenNr(rahmenNr);
    	setBild(bild);
    	setStandort(standort);
    	setPreis(preis);
    	    	
    }
    
    /**
     * Gets the value of the bild property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBild() {
        return bild;
    }

    /**
     * Sets the value of the bild property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBild(String value) {
        this.bild = value;
    }

    /**
     * Gets the value of the standort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandort() {
        return standort;
    }

    /**
     * Sets the value of the standort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandort(String value) {
        this.standort = value;
    }

    /**
     * Gets the value of the hersteller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHersteller() {
        return hersteller;
    }

    /**
     * Sets the value of the hersteller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHersteller(String value) {
        this.hersteller = value;
    }

    /**
     * Gets the value of the rahmenNr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRahmenNr() {
        return rahmenNr;
    }

    /**
     * Sets the value of the rahmenNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRahmenNr(Integer value) {
        this.rahmenNr = new BigInteger(value.toString());
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link ModelType }
     *     
     */
    public ModelType getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelType }
     *     
     */
    public void setModel(ModelType value) {
        this.model = value;
    }

    /**
     * Gets the value of the vergebenAn property.
     * 
     * @return
     *     possible object is
     *     {@link VergebenAnType }
     *     
     */
    public VergebenAnType getVergebenAn() {
        return vergebenAn;
    }

    /**
     * Sets the value of the vergebenAn property.
     * 
     * @param value
     *     allowed object is
     *     {@link VergebenAnType }
     *     
     */
    public void setVergebenAn(VergebenAnType value) {
        this.vergebenAn = value;
    }

    /**
     * Gets the value of the ausleih property.
     * 
     * @return
     *     possible object is
     *     {@link AusleihType }
     *     
     */
    public AusleihType getAusleih() {
        return ausleih;
    }

    /**
     * Sets the value of the ausleih property.
     * 
     * @param value
     *     allowed object is
     *     {@link AusleihType }
     *     
     */
    public void setAusleih(AusleihType value) {
        this.ausleih = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    public int getIdAsInt() {
        return id.intValue();
    }
    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(Integer value) {
        this.id = new BigInteger(value.toString());
    }

    /**
     * Gets the value of the besitzerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBesitzerID() {
        return besitzerID;
    }

    /**
     * Sets the value of the besitzerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBesitzerID(Integer value) {
        this.besitzerID = new BigInteger(value.toString());
    }

    
    public Float getPreis() {
        return preis;
    }

    /**
     * Sets the value of the preis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPreis(Float value) {
        this.preis = value;
    }

}
