//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 05:14:24 PM CEST 
//


package orgExampleFahrradverleih;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fahrraeder_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fahrraeder_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fahrrad" type="{http://www.example.org/FahrradVerleih}fahrrad_type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fahrraeder_type", propOrder = {
    "fahrrad"
})
public class FahrraederType {

    @XmlElement(required = true)
    protected List<FahrradType> fahrrad;
    
    /********* EIGENER TEIL **********/
    public FahrraederType() {
    	this.fahrrad = new ArrayList<FahrradType>();
    }

    /**
     * Gets the value of the fahrrad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fahrrad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFahrrad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FahrradType }
     * 
     * 
     */
    public List<FahrradType> getFahrrad() {
        if (fahrrad == null) {
            fahrrad = new ArrayList<FahrradType>();
        }
        return this.fahrrad;
    }
    

    /********* EIGENER TEIL **********/
    public FahrradType getOneFahrrad(int index) {
    	return this.fahrrad.get(index);
    }
        
    /********* EIGENER TEIL **********/
    public FahrradType getOneFahrradById(int fahrradId) {
    	for(int i=0;i<this.getFahrradListSize();i++){
			FahrradType fahrrad = this.fahrrad.get(i);
			if(fahrrad.getId().intValue() == fahrradId){
				return fahrrad;
			}
		}
    	return null;
    }
    
    public void setFahrraeder(ArrayList<FahrradType> fahrraeder) {
		this.fahrrad = fahrraeder;
	}
    
    /********* EIGENER TEIL **********/
    public void addFahrrad(FahrradType fahrrad) {
    	this.fahrrad.add(fahrrad);
    }
    
    /********* EIGENER TEIL **********/
    public void deleteFahrrad(FahrradType fahrrad) {
    	this.fahrrad.remove(fahrrad);
    }
    
    /********* EIGENER TEIL **********/
    public void deleteUserFahrraeder(int besitzerId) {
    	for(int i=0;i<this.getFahrradListSize();i++){
			FahrradType fahrrad = this.fahrrad.get(i);
			if(fahrrad.getBesitzerID().intValue() == besitzerId){
				this.fahrrad.remove(fahrrad);
			}
		}
    }
    
    /********* EIGENER TEIL **********/
    public int getFahrradListSize(){
    	return this.fahrrad.size();
    }
    
    /********* EIGENER TEIL **********/
    public int getLastFahrradId(){
    	return this.fahrrad.get(this.fahrrad.size()-1).getId().intValue();
    	
    }



}
