//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 05:14:24 PM CEST 
//


package orgExampleFahrradverleih;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for model_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="model_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Mountainbike"/>
 *     &lt;enumeration value="Rennraeder"/>
 *     &lt;enumeration value="BMX"/>
 *     &lt;enumeration value="Citybike"/>
 *     &lt;enumeration value="KinderFahrraeder"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "model_type")
@XmlEnum
public enum ModelType {

    @XmlEnumValue("Mountainbike")
    MOUNTAINBIKE("Mountainbike"),
    @XmlEnumValue("Rennraeder")
    RENNRAEDER("Rennraeder"),
    BMX("BMX"),
    @XmlEnumValue("Citybike")
    CITYBIKE("Citybike"),
    @XmlEnumValue("KinderFahrraeder")
    KINDERFAHRRAEDER("KinderFahrraeder");
    private final String value;

    ModelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ModelType fromValue(String v) {
        for (ModelType c: ModelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
